### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by calvinfo** [segment-boneyard/transform-legacy#1]
This repo looks good to open source to me, any objection @yields ? We'll need it for adding to the webhooks.

**Comment by yields** [comment]
tough call, we are going to remove it anyway after a month or so yeah ?
so maybe just copy it over to [integrations/lib/webhooks](https://github.com/segmentio/integrations/tree/master/lib/webhooks).

**Comment by calvinfo** [comment]
eh, I think this is probably easier and cleaner yeah? we could publish it too and if anyone complains about not the new format we can point them to this repo.

**Comment by yields** [comment]
oh yeah good point!
